#!/bin/bash

set -e

ROOT=$(dirname $0)/..
cd ${ROOT}

if [ -z ${RAX_API_KEY} ]; then
  echo "You must provide RAX_API_KEY to publish."
  exit 1
fi

git pull
script/cross
script/checksum
output=$(script/publish-to-test)
echo "$output"
cdn_ssl_base_url=$(echo "$output" | grep 'cdn_ssl_base_url' | awk '{print $2}')
script/verify $cdn_ssl_base_url
if [ $? -ne 0 ]; then
    exit $?
fi
output=$(script/publish-to-prod)
echo "$output"
CS_REBOOT_INFO_APP_VERSION=$(echo "$output" | grep 'app_version_published' | awk '{print $2}')
script/update-version-in-readme
